# Generated by Django 5.1.7 on 2025-03-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_content_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_content',
        ),
    ]
