# Generated by Django 5.1.7 on 2025-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
